name: Build and Run
 
on: 
    push:
        branches: [master]
 
jobs:
  build:
 
    runs-on: windows-latest
    
    env: 
      Solution_Name: CaseStudyRough.sln                         
#      Test_Project_Path: your-test-project-path                 
 
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
#     - name: Run unit tests
#       run: dotnet test --no-build --configuration Release
# Restore paages, MSBUild the app, run the app
    - name: Build the App
      shell: cmd
      run: call build.bat 

    # Run the app
    - name: Run the App
      shell: cmd
      run: call run.bat 
